name:                opengraph-scraper
version:             0.1.0.0
github:              "mel-brown/opengraph-scraper"
license:             BSD3
author:              "Melanie Brown"
maintainer:          "brown.m@pm.me"
copyright:           "2020 Melanie Brown"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mel-brown/opengraph-scraper#readme>

dependencies:
  - aeson
  - base    >= 4.7 && < 5
  - blaze-html
  - happstack-server
  - scalpel

library:
  source-dirs: src

executables:
  opengraph-scraper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opengraph-scraper

tests:
  opengraph-scraper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opengraph-scraper
